### ISSUE TITLE
Add README for runtime compatibility !!!

### ISSUE THREAD

**Issue by Reichmann-M** [Michael-Rienessl/dhbw-webproject#49]
Röthig requested this

**Comment by Niklas227** [comment]
> Add: 'Use a 16:9 or 16:10 monitor to display the graphs page.'

@Reichmann-M ist das noch aktuell

**Comment by Reichmann-M** [comment]
> > Add: 'Use a 16:9 or 16:10 monitor to display the graphs page.'
> 
> @Reichmann-M ist das noch aktuell

Das ist nicht mehr aktuell, da Patrick mit #63 die 4:3 incompatibility gefixt hat

**Comment by Niklas227** [comment]
Done
